# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted # Ensure this matches your runner's setup

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Checkout the code from the repository
    - uses: actions/checkout@v4

    # Set up the specified Node.js version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies using npm
    - name: Install dependencies
      run: npm ci

    # Step 4: Create .env file with secrets
    - name: Setup environment variables
      run: |
        touch .env
        echo "DEVELOPER=${{ secrets.developer }}" > .env

    # Restart application using PM2
    - name: Restart application with PM2
      run: |
        pm2 restart 0
        pm2 save # Save the PM2 process list

